[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Base Sepolia (Testnet)
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

# Etherscan configuration for contract verification
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }

# Test configuration
[profile.default.fuzz]
runs = 256

# Gas reports
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config